language: python
dist: xenial
python:
- '3.6'
before_install:
- echo "before install"
- pip3 install awscli
install:
- echo "install"
script:
- echo "script"
- sh travis.sh
env:
  global:
  # AWS_DEFAULT_REGION
  - secure: SPS2cYUsAGWBYlLdDTnb+roHfbZMQzIhB+9yL6EgpgoZx/CU6QeB+g2FoLKqap0WYLf0KjlqrpVk8X+0hMy/+r6icjymzBj58ZNKo0HtyGai1TuoZ4wuXzs9TS4mX3zOG1lql5c7kL+Ba2Y06gv/pkXHOz8VHIAnsqZJIeXUJD3GLZlKtc5GNJ5sL2+tvAYWWOavr7Ok2Zrq/M/IGZp7D8ZWnxcM2RNC1TJjUZEXUutE2G51NZT8XaKUQITnWAjJO+m0JsvemTQLvi5CvZCo3dX4Yi+aYwCEypaiebFntBozhCRfjkDd3BlTx8/IgrClAngFslxJbaVik5j+xyFzSRCIuwNJexc1rMzMI0zQE8ngZ4qgIGPJNRWqdKw4bRLidfESOKEYTQxzq83mAAzqdkH+1VZx4QKsG8qNXOnzzghMF4oxYkNRdGF4q2lIbkuCyDoWZvlbPx2Zlc6RH1drmslBt0OTreaeW+E522laIwH0UG1LN7XNlY/i495aWxBvMBf4x9cj4+7Rlrco/qAipo1mXcPLXy9kWqiZxP/BqnANNpinykSve7Nh0vicerwZBKGjsaXFfmhfGPjCJADbWdk5IK8oQeWfnjqWI1KZ2oK2X55RvxuTc206+Ew6YDdt9pBldB8Z2gtXmw5NB7e5ALYbzCCdm+9/4a04yU/H5Wc=
  # AWS_ACCESS_KEY_ID
  - secure: d96pYhwp0Ef2nQ6OK1thVPleed1pizJVkf2NziLM4lh56Ny6QdkrOoAZRSLKuL0b5NEwoPra7NJ6ssuMEsgGXbWr4Ro4Y1PfjmR4W3cwAlzrK8nTqAMIjASdwO/OkrjJNLIUHJFr4nT+EkbcvGrAmIsAjiGv6UBiLpGCWBFweduqzdUtkvD5Qy13x9e+mSbphjXTROYrhjH6c0JMHkdj4gqvc+6IyDkHzr+pYecIFutiegIyh1LiP4Mch2TaaNqq8IHWXfL0MQNXqAbmoEt3qpUC732CMUHap9k/JTHDSQFJX1odlup4jam2e+eAmi8VnnqXm2fotIDKbtBTJYCsMvhD2MITbFRMyKgh4zX75/IupMw1zIcJvL44rdizj07AWXzMZwpE0wB9+AplNIww7sERZwomkj87aDqTlt51QgFQNxJnb0dAeKA+l+v7uYZfjzklkS74EeUvfsOufCWdWYk2/JGWwqK0dxNbS34sySClsyjMezRU+gYWfRxCEWylaIUaURgZcwJJxIXd+D9xrQ2AD0jBOztdnpzYtjglg6VaOlIvPvrRGBrskUi1slqKIIUJQ1zlKtnJaAXhvbjRnYg+8MrwJXrDEgKSKkgMH2OS6qq5SAuLCccPAMQWZTXSuYtxgRxemsT/6QcaIEINgPSa7IgaBMfloCLbx+nHPeA=
  # AWS_SECRET_ACCESS_KEY
  - secure: z9lgHrU2J7QAp3oR6q4+OHemfXE3LKCB0LXTZ6Iqd1rhCAohrr7bT4eHrJ8jzfhOy75e1nWF7rcyO96Rgqf9ejsidAn+EO5N7jbTCFzoZ8zDwj0OMjeXVtlotfELVQ+2RWVCUnKK7WaKwKn3BNrNphA8FG1texTyJEDj5lyQw8NevP2rjQbWl1ysyxB46GDD70B3gbpy1mdz5heMxi6Mv2KipQ/1I3dYVXExvbDyVX82JrNDtRRCfb8M4qG7bQ4bzbAZgm7eyhKPDV/76s0b9wt8nSKMvHiD7oUJxRIk0gz96H7tq7wrU6JXIJ1avBRh6goueGQ4wO/oKNRKClrLyz5QbJ8Cn+2bN1sCiDUkGMXvLxpOYV6Dd6H6wmR/tDxWOZGoTfQwO+rrFCAm6I3IFAJZ+GsNm1+EHLNd/BdoyLYW0BaQFfHDbEzDB1BlOIKrq47w7zALZyadlAtyFaUGoP8X+yqAW8sjZxSUteZ/XUP5/i356iFuUvqQhweew37iO+ygxGxr5xRFnEVHjEh/Zg4bXt0A1CvjRYNQjgNoxkrg/lwQtOqpgfFiaYnQIdZTCbuHzfRsE7Ja7J3F7A6OgXi0rskcSshifZ5yMzL6AUvWij+MLkN2sW07mXgRopxMjpO4hyd98KoyvPT6gezR6lHUTPYjyNI3mPxxMzYWxvw=
