language: python
dist: xenial
python:
- '3.6'
before_install:
- echo "before install"
- pip3 install awscli
install:
- echo "install"
script:
- echo "script"
- sh travis.sh
env:
  global:
  - AWS_DEFAULT_REGION=eu-central-1
   # AWS_ACCESS_KEY_ID
  - secure: GIfehYjwRjqQXHauqjA2WiPORU+P4uFxApktBSa/Xoo8TgklGzu7wK4c9dst8ChMUOyCQuy0MXouuUKBCWlqbj6oqFeNcRNaO66Ok4fR/wiDuN1MST3XaGtYb6/FOkAYu3zGlIrw5URTAx/iqK2byafynZC5Cqhxr9N95V2OLPKCZsK5g6LRKZSVY8DpdxsIheUV1ecUL8oVEW2n36eSH/EppYPcKhYvr7ATdrk5osu7r5DOKxbBu+3k/plModqqKQtCyc1m0yKZo7dAAkH89Mp4KOm2fPpwbu0RtnPxE2J7S/Jgcjs2IDJvSLemhUF4c3b6TWmU6pA644UpkWFO30Ra+rIFs7cnWWSCVbGaDqYuKvTheexVKlupSnIAy7P+Cl+VGC1ZBF3tkAxfb+7dDTZ2c7CDLrM6Kwqgorv6AT4QUiPKiWIyoc0kv+py/81EWI0lQmC5pERaW0BUxRsxxd6xPK13rKl2RbVlUHeeza4af+ePHN27Hxz90YuoH3G20bQq9J8s5PQmwFBcYGqbJVA8G7nU/HEmG+EDfFFOlfG69P9BoHaRUHKydmfYS9o3aB4V+O2MkL+Dd8YUu8Kt1uu6QeF8RB5ltL1HzB9smNgmTQoaRNoFHvFxNtdCm7kHdMXcRnCSouEpXPe3dpC6+kCoAIg4pypjRbkq5y1Dq78=
   # AWS_SECRET_ACCESS_KEY
  - secure: mA2BAhMEXGj/PKKio/+/tQzUtKZWUN0ClgPyLJKYhhp1bZl5CAVdeaP4k/1u4juB+YIuZj8DumHXrkPahlsedWUYkDUfpq6mi2PugCWzXDDCEftRvKGFQ6WN5WZwpBXqTIokpF5zxEITIQzYmex8qBryMiWWzhh+V6gi80dzsPzVDfDyQO7p4LJuWEw9M4exAImF4VgP90OxuopRlsrd1G6T78L859I6deyIfzVFaplO4nL8r8j+uaAwYA0ZMdNxhqBvbj5tBJ0zVWxOh/MCwfgz5nEESgL73M9fqVrLIVAocKVOoM6URZJnEKupiHkQWvWoIaAMxXiNjO/NPh/SBRao2fqVVK6Dbsv7fnhctCQejYmeJZzxqoVgvNHVa9ZH/gQ7LTHa13YostU06P8TG8wOdD8yL0yCkPx8YP1JrCaB7jm5tiTBvNGNc92mL4m+2ZY8LYAP4+CTXZx5SX68s5tNz5BU5Tb08DV0c4S5A755I+lfqJ0yZrcNyyXAbjjsaGl0LnbWMQlSSTIAj4YN970VIQrtYacXIEc9MdL3pwM5RtVQOBhz7J9aVpJ7C3AOcItrSibbvDsXlqVz2W1gHkKohdQNS82Q5EudtisSeo6jBLURTI8eg+4Pojo2VcZ7yfEYR9+eNWPLJAzeyDnfZU7vRXqMk/l4HcE3n1qaQ+8=
