= About

AWS Lambda function that extracts audio, tags it and uploads it to S3.

== Version

include::VERSION[]

== Dependencies

* `python3` and `pip3` (make sure that `./build` is run using these)
* `ffmpeg` and `ffprobe` (version `3.3`, x86-64 static Linux binaries)
* `tagit` (basics `taglib` based tagger)
* `bs1770gain` (command-line replaygain scanner)
* `youtube-dl` (version `2018.9.10`)

== Making a Release

=== Remote

Whenever a commit is made https://github.com/kohanyirobert/aws-lambda-sniff/actions?query=workflow%3A.github%2Fworkflows%2Fdeploy.yml[GitHub Actions is triggered].
A new package is created with the latest `youtube-dl` dependencies and it is pushed to AWS Lambda automatically.

=== Local

NOTE: `youtube-dl` can only use `ffmpeg`, `ffprobe` and other binaries if they're packaged as executable files.

```
./deploy.sh
```

== Environment Variables

* `BUCKET` - the S3 bucket name to upload audio files to.
* `WORK_DIR` - the directory path to download temporary files, etc. (e.g. `/tmp`).
* `NORMALIZE_FILENAME_SRC` - string of characters which are replaced in filenames (e.g. `/*`)
* `NORMALIZE_FILENAME_DST` - string of characters which are used as replacement in filenames (e.g. `-_`).
* `NORMALIZE_FILENAME_DEL` - string of characters which are removed from filenames (e.g. `:`).

*Note*: `NORMALIZE_FILENAME_SRC` and `NORMALIZE_FILENAME_DST` are used together with `str.maketrans` as the functions two arguments.
