= About

AWS Lambda function that extracts audio, tags it and uploads it to S3.

== Version

include::VERSION[]

== Dependencies

* `python3` and `pip3` (make sure that `./build` is run using these)
* `ffmpeg` and `ffprobe` (version `3.3`, x86-64 static Linux binaries)
* `tagit` (basics `taglib` based tagger)
* `bs1770gain` (command-line replaygain scanner)
* `youtube-dl` (version `2018.9.10`)

== Making a Release

NOTE: Didn't seem to work when deployed from Windows.
Probably fails because the Windows version of the `youtube-dl` Python dependency does something differently than on Linux.
Use Vagrant.

```
./build.sh
./package.sh
./upload.sh
./deploy.sh
```

== Environment Variables

* `BUCKET` - the S3 bucket name to upload audio files to.
* `WORK_DIR` - the directory path to download temporary files, etc. (e.g. `/tmp`).
* `NORMALIZE_FILENAME_SRC` - string of characters which are replaced in filenames (e.g. `/`)
* `NORMALIZE_FILENAME_DST` - string of characters which are used as replacement in filenames (e.g. `-`).

*Note*: `NORMALIZE_FILENAME_SRC` and `NORMALIZE_FILENAME_DST` are used together with `str.maketrans` as the functions two arguments.
